#!/bin/bash

sudo apt update -qq
sudo apt install -y -qq zip unzip wget curl

# Crear carpeta de servidor si no existe:
mkdir -p ~/server
cd ~/server

# ======================================== #
# ========== CONFIGURACIÓN =============== #
# ======================================== #
BEDROCK_VERSION="latest"
SERVERNAME="Bedrock Dedicated Server"
GAMEMODE="survival"
DIFFICULTY="easy"
CHEATS="false"

# ======================================== #
# ====== DESCARGA DEL SERVIDOR BDS ======= #
# ======================================== #

RANDVERSION=$(echo $((1 + $RANDOM % 4000)))

if [ "$BEDROCK_VERSION" == "latest" ]; then
    echo -e "\n🔍 Descargando última versión de Bedrock Server..."
    curl -sL \
        -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64)" \
        -o versions.html.gz \
        "https://www.minecraft.net/en-us/download/server/bedrock"

    DOWNLOAD_URL=$(zgrep -o 'https://minecraft.azureedge.net/bin-linux/[^"]*' versions.html.gz | head -1)

    if [ -z "$DOWNLOAD_URL" ]; then
        echo "❌ ERROR: No se pudo obtener la URL de descarga."
        exit 1
    fi
else
    echo -e "\n Descargando version específica: $BEDROCK_VERSION"
    DOWNLOAD_URL="https://minecraft.azureedge.net/bin-linux/$BEDROCK_VERSION.zip"
fi

DOWNLOAD_FILE=$(basename "$DOWNLOAD_URL")

# ======================================== #
# ========== BACKUP DE ARCHIVOS ========== #
# ======================================== #

echo "📦 Realizando respaldos..."
[ -f server.properties ] && cp server.properties server.properties.bak
[ -f permissions.json ] && cp permissions.json permissions.json.bak
[ -f whitelist.json ] && cp whitelist.json whitelist.json.bak

rm -f versions.html.gz

echo "⬇ Descargando: $DOWNLOAD_URL"
curl -sL -o "$DOWNLOAD_FILE" "$DOWNLOAD_URL"

echo "📤 Extrayendo archivos..."
unzip -o "$DOWNLOAD_FILE" >/dev/null

echo "🧹 Limpiando archivos..."
rm -f "$DOWNLOAD_FILE"

echo "♻ Restaurando configuración si existe..."
[ -f server.properties.bak ] && cp server.properties.bak server.properties
[ -f permissions.json.bak ] && cp permissions.json.bak permissions.json
[ -f whitelist.json.bak ] && cp whitelist.json.bak whitelist.json

chmod +x bedrock_server

echo "✅ Servidor Bedrock instalado correctamente."


# ======================================== #
# ======== INSTALAR PLAYIT.GG ============ #
# ======================================== #

echo "⬇ Instalando Playit.gg (última versión)..."

wget -q "https://github.com/playit-cloud/playit-agent/releases/latest/download/playit-linux-amd64" -O playit
chmod +x playit

echo "✅ Playit.gg instalado correctamente."
echo ""
echo "🎉 Instalación completa."
echo ""
echo "-- ¿Deseas iniciar el servidor ahora? --"
echo "1) Sí"
echo "2) No"

read -r opcion


if [ "$opcion" == "1" ]; then
    echo "Iniciando servidor..."
    ./bedrock_server
fi
